<a href="https://colab.research.google.com/github/simonvelezt/Analitica/blob/main/reto_2_simon_velez_t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. se cargan las librerias

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier

from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


2. se procede con la carga de archivos

In [ ]:
nxl='/content/drive/MyDrive/ANALISIS DE DATOS/2. BD1_Travel_Data_int.xlsx'
XDB=pd.read_excel(nxl,sheet_name=0)
XDB=XDB.dropna()
XDB.head(100)

XD=np.array(XDB[['College','FoodSpend','Income','TravelSpend']])
print(XD)

yd=np.array(XDB['CreditCard'])
print(yd)



['Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'No'
 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No'
 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No'
 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No'
 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No'
 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'Yes'
 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes

3. se crea el modelo

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

# Encode 'CreditCard' column to numerical values
le = LabelEncoder()
XD[:,0] = le.fit_transform(XD[:,0])
print(XD)
yd = le.fit_transform(XDB['CreditCard'])
print(yd)

mar = DecisionTreeClassifier(criterion='gini',max_depth=4)
mar.fit(XD,yd)
ydp = mar.predict(XD)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(yd,ydp)
print(cm)

VN=cm[0,0]
FP=cm[0,1]
FN=cm[1,0]
VP=cm[1,1]

exactitud=(VP+VN)/(VP+VN+FP+FN)
print( "La exactitud es:",exactitud)

sensibilidad=VP/(VP+FN)
print( "La sensibilidad es:",sensibilidad)

especificidad=VN/(VN+FP)
print( "La especificidad es:",especificidad)

[[1 5472.43 49150 827.4]
 [0 9130.73 47806 863.55]
 [0 4450.67 46050 1180.05]
 ...
 [0 3585.86 42250 2251.95]
 [1 1833.95 60248 2000.25]
 [0 6205.97 58520 3667.5]]
[1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0
 1 0 1 0 0 1 1 1 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0
 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0
 0 0 0 0 0 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 0 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0
 0 0 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0
 0 1 1 1 1 

3. Arbol

In [ ]:
from sklearn.tree import export_graphviz
from pydotplus import graph_from_dot_data

vs= ['College','FoodSpend','Income','TravelSpend']
dot_graph=export_graphviz(mar,feature_names=vs)
graph=graph_from_dot_data(dot_graph)
graph.write_png('arbol.png')

True

4. pronostico nuevos clientes

In [ ]:
XDB2=pd.read_excel(nxl,sheet_name=1)
XDB2=XDB2.dropna()
XDB2.head(100)

XD2=np.array(XDB2[['College','FoodSpend','Income','TravelSpend']])
# Encode 'College' column in XD2 using the same LabelEncoder
XD2[:, 0] = le.transform(XD2[:, 0])  # Use the previously fitted LabelEncoder 'le'
print(XD2)

ydp2=np.array(mar.predict(XD2))
print(ydp2)

[[0 2892.9 65982 2151.6]
 [1 6017.66 53986 2002.5]]
[0 0]
